"""Canonical, engine-independent NoöPunk RPG rules."""

from .core import (
    ATTRIBUTE_DEFINITIONS,
    ATTRIBUTE_IDS,
    BLOCKED_TRAINED_ONLY,
    DIFFICULTIES,
    DIFFICULTY_MEANINGS,
    HUMAN_ATTRIBUTE_INTERPRETATION,
    UNSKILLED_PENALTY,
    AttributeSet,
    CheckResult,
    HumanAttributes,
    OpposedResult,
    SkillAccess,
    UnknownDifficulty,
    compare_opposed,
    difficulty_meaning,
    difficulty_target,
    generate_human_attributes,
    human_modifier,
    roll_3d6,
    resolve_check,
)

__all__ = [
    "ATTRIBUTE_DEFINITIONS",
    "ATTRIBUTE_IDS",
    "BLOCKED_TRAINED_ONLY",
    "DIFFICULTIES",
    "DIFFICULTY_MEANINGS",
    "HUMAN_ATTRIBUTE_INTERPRETATION",
    "UNSKILLED_PENALTY",
    "AttributeSet",
    "CheckResult",
    "HumanAttributes",
    "OpposedResult",
    "SkillAccess",
    "UnknownDifficulty",
    "compare_opposed",
    "difficulty_meaning",
    "difficulty_target",
    "generate_human_attributes",
    "human_modifier",
    "roll_3d6",
    "resolve_check",
]
