#!/usr/bin/env python3
"""Regenerate the measured tables in docs/design/ISSUE_200_ASPECTS_PROTOTYPE.md.

Same discipline as tools/issue200_kernel_report.py: every number in that document comes from
here, and the dice probabilities are EXACT (rational), so nothing is blamed on a seed.

Run: python3 tools/issue200_aspects_report.py
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from rules import aspects_prototype as ap
from rules.kernel_prototype import MAX_SITUATIONAL_STEPS


def rule(title: str) -> None:
    print(f"\n### {title}")


def pct(value) -> str:
    return f"{float(value) * 100:.1f}%"


def pp(value) -> str:
    return f"{float(value) * 100:+.1f}pp"


def main() -> int:
    print("# Measured: the aspects / resource / consequence layer")
    print()
    print("Generated by `tools/issue200_aspects_report.py`. Dice probabilities are **exact**")
    print("(rational, 81 equally likely 4dF outcomes), so no figure depends on a seed. Every")
    print("parameter below is DRAFT pending calibration, per #200.")

    rule("1. Why 'bounded' cannot mean Fate's +2")
    print("The 4dF roll itself, before anything is added:\n")
    print("| roll | -4 | -3 | -2 | -1 | 0 | +1 | +2 | +3 | +4 |")
    print("| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |")
    counts = ap.fdf_outcome_counts()
    total = sum(counts.values())
    print("| share | " + " | ".join(f"{counts[v] / total * 100:.2f}%" for v in range(-4, 5)) + " |")
    print(f"\n**{pct(ap.spread_of_the_roll())} of all outcomes fall within +/-1.** That is the roll's")
    print("own typical spread, and it is the yardstick for what a 'bounded' modifier may be.\n")
    print("| invoked bonus | P(success) at step 0 | gain |")
    print("| --- | --- | --- |")
    for bonus, (probability, gain) in ap.bonus_table().items():
        if bonus <= 4:
            print(f"| +{bonus} | {pct(probability)} | {pp(gain)} |")
    print(f"\nA single **+1** moves the odds {pp(ap.value_of_bonus(1))} -- a nudge, and the value the")
    print(f"prototype adopts (:data:`ASPECT_INVOKE_BONUS = {ap.ASPECT_INVOKE_BONUS}`). A **+2** moves them")
    print(f"{pp(ap.value_of_bonus(2))}, turning 'likely' into 'near-certain'; **+3** reaches")
    print(f"{pct(ap.success_probability(3))}. So #200's 'bounded modifiers' is narrower than Fate's")
    print("default, and +1 is where that line lands on THIS die.")

    rule("2. The bound, and the exploit it prevents")
    print(f"Cap: at most **{ap.MAX_INVOCATIONS_PER_ROLL}** invocation per roll.\n")
    print("| aspects invoked | uncapped P(success) | capped P(success) |")
    print("| --- | --- | --- |")
    for n in (1, 2, 3, 4, 6):
        print(f"| {n} | {pct(ap.stacked_success_probability(invocations=n, cap=False))} "
              f"| {pct(ap.stacked_success_probability(invocations=n, cap=True))} |")
    uncapped_auto = next(n for n in range(1, 12)
                         if ap.stacked_success_probability(invocations=n, cap=False) == 1)
    print(f"\n**An uncapped stack of {uncapped_auto} aspects reaches exactly 100%** -- absolute")
    print("auto-success, with no die roll that can fail. That is the 'uncapped numerical exploit'")
    print("#200 names, and it is reachable with four tags. The cap is not tidiness; it is the")
    print("difference between a game and a formality.")
    print("\nFor comparison, the kernel prototype's cap on situational modifiers is")
    print(f"+/-{MAX_SITUATIONAL_STEPS} steps and its uncapped branch walks past the whole 4dF range.")
    print("A one-step aspect is deliberately smaller than that: aspects are frequent, so each")
    print("one has to be worth less.")

    rule("3. The narrative resource: pool, rate and compel break-even")
    print(f"Starting pool **{ap.NARRATIVE_POOL_START}**, costing **{ap.TOKENS_PER_INVOCATION}** per")
    print(f"invocation, gaining **{ap.TOKENS_PER_COMPEL}** per accepted compel (all DRAFT).\n")
    print("| invocations per scene | scenes the pool sustains | compels needed per scene |")
    print("| --- | --- | --- |")
    for rate in (1, 2, 3):
        print(f"| {rate} | {float(ap.tokens_per_scene(rate)):.1f} | "
              f"{float(ap.compel_break_even(rate)):.1f} |")
    print("\nAt one invocation per scene the pool funds three scenes before it needs compels; at")
    print("three per scene it funds one. That is the whole pace lever, and it is why the compel")
    print("rate is not a footnote: **the resource only refills by accepting complications**, which")
    print("is #200's Narrativist requirement doing mechanical work rather than decorating it.")

    rule("4. Permission use: free, deterministic, and worth no number")
    tag = ap.Aspect(name="UNSA forensic credentials", permits="examine the sealed evidence locker")
    print(f"`{tag.name}` permits `examine the sealed evidence locker`:")
    print(f"- `permits_action('examine the sealed evidence locker')` -> "
          f"**{tag.permits_action('examine the sealed evidence locker')}**")
    print(f"- `permits_action('override the colony reactor')` -> "
          f"**{tag.permits_action('override the colony reactor')}**")
    print("\nPermission use rolls nothing and adds nothing. It establishes what is fictionally")
    print("possible, which is what #200 asks tags to do FIRST -- and it is the one aspect use that")
    print("cannot be gamed by stacking, because it grants no number to stack.")

    rule("5. Consequences against the authored ladder")
    print(f"The authored vocabulary is `RULEBOOK.md` section 51: {', '.join(ap.CONSEQUENCE_STATES)}.")
    print("The tests assert this prototype against that text.\n")
    harm = ap.HarmState()
    harm.record("Scratched")
    print(f"- after recording one state: worst = **{harm.worst}**, taken out = **{harm.taken_out}**")
    worse = ap.HarmState(states=["Scratched", "Critical"])
    print(f"- after the fiction establishes something worse: worst = **{worse.worst}**, "
          f"taken out = **{worse.taken_out}**")
    full = ap.HarmState(consequences=ap.MAX_CONSEQUENCES)
    print(f"- consequence penalty is bounded at {ap.MAX_CONSEQUENCES} x "
          f"{ap.CONSEQUENCE_PENALTY_STEPS} = **{full.penalty_steps()} steps** maximum, even if a")
    print(f"  character somehow carries more: {ap.HarmState(consequences=99).penalty_steps()} steps")
    print(f"- harm advancing by arithmetic (which section 51 forbids): "
          f"**{ap.ladder_progression_is_automatic()}**")
    print("\nThe states are recorded, never computed. Section 51 is explicit that a successful")
    print("attack does not automatically advance this and repeated harm does not automatically")
    print("step along it, so a numeric stress track would contradict canon rather than extend it.\n")
    print("The numeric counterfactual, measured only so the difference is visible. Note the")
    print(f"baseline: an UNADJUSTED 4dF roll already succeeds {pct(ap.success_probability(0))} at")
    print("step 0, because a tie goes to the roller -- so these paces are generous by construction:")
    print()
    print("| stress boxes | expected exchanges to fill |")
    print("| --- | --- |")
    for boxes in (2, 3, 4, 6):
        print(f"| {boxes} | {float(ap.attrition(boxes=boxes)):.1f} |")
    print("\nA numeric track answers 'how many hits', which is precisely the question section 51")
    print("declines to make automatic. So this table is a design observation for the author, never")
    print("a proposed rule.")

    rule("6. Relationships and scene stakes, and what stays open")
    print("Both are aspect-shaped in this prototype rather than separate subsystems:")
    print("- a **relationship** is a tag whose permission is social access and whose invocation is")
    print("  the same bounded step as any other aspect -- one number, one cap, no special case;")
    print("- **scene stakes** are a statement of what is at risk, which the compel path consumes:")
    print("  accepting the stake's complication is what refills the pool.")
    print("\nThat keeps one economy rather than three. What is deliberately NOT proposed: names for")
    print("the resource or the states beyond the authored ones, any new Skill, any change to the six")
    print("STATs, and any damage arithmetic. Section 51's transition rules remain the author's.")

    rule("7. Where this prototype stands")
    print("- Every parameter is DRAFT and centralised at the top of the module, so calibration is a")
    print("  one-place edit rather than a hunt.")
    print("- The dice math is exact, and `tests/test_issue200_aspects_prototype.py` cross-checks it")
    print("  against the kernel prototype's independently-computed figures.")
    print("- The consequence vocabulary is asserted against `RULEBOOK.md` section 51, so this file")
    print("  cannot drift from canon quietly.")
    print("- The canonical engine, `data/rules/core.json` and the six STATs are untouched, and the")
    print("  tests assert that too.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
