#!/usr/bin/env python3
"""Regenerate the measured tables in docs/design/ISSUE_200_KERNEL_PROTOTYPE.md.

Issue #200 asks for the numerical migration to be *tested* before it is locked. This
prints the evidence behind that document, so the numbers in it are reproducible rather
than asserted:

    PYTHONPATH=src python3 tools/issue200_kernel_report.py

Deterministic: every figure comes from a fixed seed, so two runs agree.
"""

from __future__ import annotations

import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from rules.core import DIFFICULTY_LADDER, SKILL_LEVEL_MAX, STAT_MAX
from rules.kernel_prototype import (
    CANDIDATES,
    FDF_COUNT,
    IS_CANONICAL,
    LADDER_LABELS,
    LADDER_MAX,
    LADDER_MIN,
    MAX_SITUATIONAL_STEPS,
    clamp_step,
    exact_opposed_probabilities,
    exact_success_probability,
    expected_4df_distribution,
    hits_to_takedown,
    legacy_dv_to_step,
    p_success_legacy,
    rating_step,
    resolve_legacy,
)

TRIALS = 40_000
SEED = 20261010

PROFILES = (
    ("weak", 2, 1),
    ("competent", 5, 5),
    ("mixed", 10, 1),
    ("specialist", 8, 8),
    ("top", STAT_MAX, SKILL_LEVEL_MAX),
)


def rule(title: str) -> None:
    print(f"\n### {title}\n")


def pct(value) -> str:
    """Format a probability (float or exact Fraction) as a percentage."""
    return f"{float(value) * 100:.1f}%"


def step_counts(candidate: str) -> dict[int, int]:
    """How many of the 100 (STAT, Skill) pairs land on each step. Spread, not range."""
    counts = {s: 0 for s in range(LADDER_MIN, LADDER_MAX + 1)}
    for stat in range(1, 11):
        for skill in range(1, 11):
            counts[clamp_step(CANDIDATES[candidate](stat, skill))] += 1
    return counts


def legacy_takedown(*, stat: int, skill: int, target: int, stress: int, trials: int, seed: int) -> float:
    """Exchanges to fill a stress track on the CANONICAL engine, as a lethality proxy."""
    rng = random.Random(seed)
    total = 0
    for _ in range(trials):
        remaining, exchanges = stress, 0
        while remaining > 0 and exchanges < 400:
            exchanges += 1
            if resolve_legacy(stat=stat, skill=skill, target=target, rng=rng).success:
                remaining -= 1
        total += exchanges
    return total / trials


def main() -> int:
    print("# Kernel prototype measurements (#200)")
    print(f"\nGenerated by `tools/issue200_kernel_report.py`. Dice probabilities are EXACT"
          f" (rational, no seed); lethality is sampled at {TRIALS:,} trials with seed {SEED}.")
    print(f"`IS_CANONICAL = {IS_CANONICAL}`. This does not modify `data/rules/core.json`.")

    rule("1. The legacy benchmark reproduces the recorded canon")
    print("`data/rules/core.json` records Novice (STAT 4 + Skill 1) success at DV 9/13/15")
    print("as 0.7 / 0.3 / 0.1. Re-measured through the canonical engine:\n")
    print("| DV | recorded | measured |")
    print("| --- | --- | --- |")
    for target, recorded in zip((9, 13, 15), (0.7, 0.3, 0.1)):
        measured = p_success_legacy(stat=4, skill=1, target=target, trials=TRIALS, seed=SEED + target)
        print(f"| {target} | {recorded:.2f} | {pct(measured)} |")
    print("\nThe benchmark is a delegation to `src/rules/core.py`, so a comparison against")
    print("it cannot drift from the shipped engine. That is the point of testing it first.")

    rule("2. 4dF — exact distribution")
    print("| roll | " + " | ".join(str(k) for k in range(-FDF_COUNT, FDF_COUNT + 1)) + " |")
    print("| --- |" + " --- |" * (2 * FDF_COUNT + 1))
    dist = expected_4df_distribution()
    print("| chance | " + " | ".join(f"{dist[k] * 100:.2f}%" for k in sorted(dist)) + " |")
    print(f"\nMean 0, bounded to ±{FDF_COUNT}. Compare a 1d10: uniform 10% per face, and a")
    print("full ±9 swing at the tails. The ladder's tails are ~8× rarer than its centre.")

    rule("3. Rating to step — the mapping")
    print("| rating | " + " | ".join(str(s) for s in range(1, 11)) + " |")
    print("| --- |" + " --- |" * 10)
    print("| step | " + " | ".join(f"{rating_step(s):+d}" for s in range(1, 11)) + " |")
    print("| label | " + " | ".join(LADDER_LABELS[rating_step(s)] for s in range(1, 11)) + " |")
    print("\nRatings 1 and 10 sit exactly on ±3; the middle two ratings share step 0.")

    rule("4. Additive scaling — the spread, which is what #200 warns about")
    print("How many of the 100 possible (STAT, Skill) pairs land on each step. `raw` is the")
    print("**unclamped** combination, which shows what the clamp is absorbing:\n")
    headers = range(LADDER_MIN, LADDER_MAX + 1)
    print("| candidate | " + " | ".join(f"{h:+d}" for h in headers) + " |")
    print("| --- |" + " --- |" * len(list(headers)))
    for candidate in CANDIDATES:
        counts = step_counts(candidate)
        print(f"| `{candidate}` | " + " | ".join(str(counts[h]) for h in range(LADDER_MIN, LADDER_MAX + 1)) + " |")
    print("\nThe same 100 pairs, by unclamped raw sum (clamped values shown where they differ):\n")
    print("| candidate | raw range | needs clamping | collapsed to an extreme |")
    print("| --- | --- | --- | --- |")
    for candidate, raw_of in (("A_additive", lambda s, k: rating_step(s) + rating_step(k)),
                              ("B_averaged", None),
                              ("C_skill_primary", lambda s, k: rating_step(k) + max(-1, min(1, rating_step(s))))):
        if raw_of is None:
            print(f"| `{candidate}` | -3..+3 by construction | 0 of 100 | 4 of 100 |")
            continue
        raws = [raw_of(s, k) for s in range(1, 11) for k in range(1, 11)]
        out = [r for r in raws if not LADDER_MIN <= r <= LADDER_MAX]
        extremes = sum(1 for r in raws if abs(clamp_step(r)) == LADDER_MAX)
        print(f"| `{candidate}` | {min(raws):+d}..{max(raws):+d} | {len(out)} of 100 | {extremes} of 100 |")
    print("\nAll three reach every step, so 'reachability' distinguishes nothing — the raw")
    print("range does. The additive candidate wants a ±6 range on a ±3 ladder, so nearly a")
    print("fifth of its pairs are clamped and a third collapse onto the extremes.")

    rule("5. High-end disparity — and where the candidates stop differing")
    print("Effective step per profile, before any roll:\n")
    print("| candidate | weak 2+1 | competent 5+5 | mixed 10+1 | specialist 8+8 | top 10+10 |")
    print("| --- | --- | --- | --- | --- | --- |")
    for candidate in CANDIDATES:
        cells = " | ".join(f"{CANDIDATES[candidate](s, k):+d}" for _, s, k in PROFILES)
        print(f"| `{candidate}` | {cells} |")
    print("\nP(success) at ladder step 0 (an unmodified task):\n")
    print("| candidate | weak 2+1 | competent 5+5 | mixed 10+1 | specialist 8+8 | top 10+10 |")
    print("| --- | --- | --- | --- | --- | --- |")
    for candidate in CANDIDATES:
        cells = " | ".join(
            pct(exact_success_probability(candidate=candidate, stat=stat, skill=skill, difficulty=0))
            for _, stat, skill in PROFILES
        )
        print(f"| `{candidate}` | {cells} |")
    print("\nLegacy (the canonical engine), for the same profiles against the authored DVs:\n")
    print("| DV (difficulty) | weak 2+1 | competent 5+5 | mixed 10+1 | specialist 8+8 | top 10+10 |")
    print("| --- | --- | --- | --- | --- | --- |")
    for dv in DIFFICULTY_LADDER:
        cells = " | ".join(
            pct(p_success_legacy(stat=stat, skill=skill, target=dv, trials=TRIALS, seed=SEED + dv))
            for _, stat, skill in PROFILES
        )
        print(f"| {dv} (ladder {legacy_dv_to_step(dv):+d}) | {cells} |")

    rule("6. Opposed checks — symmetry, the tie rate, and the skew the Attribute buys")
    print("| candidate | equal 5+5 vs 5+5: win | tie | specialist 8+8 vs 5+5: win | mixed 10+1 vs 5+5: win |")
    print("| --- | --- | --- | --- | --- |")

    for candidate in CANDIDATES:
        equal, ties, _ = exact_opposed_probabilities(candidate=candidate, left=(5, 5), right=(5, 5))
        specialist, _, _ = exact_opposed_probabilities(candidate=candidate, left=(8, 8), right=(5, 5))
        mixed, _, _ = exact_opposed_probabilities(candidate=candidate, left=(10, 1), right=(5, 5))
        print(f"| `{candidate}` | {pct(equal)} | {pct(ties)} | {pct(specialist)} | {pct(mixed)} |")
    print("\nEqual opponents must win ~50% and the tie band must be real but a minority; a")
    print("candidate where a top-tier side never loses is a candidate that ends contests.")
    print("The mixed 10+1 column is the design question in one number: under the additive")
    print("candidate an untrained brute stays at parity, and under skill-primary he does not.")

    rule("7. Modifier stacking — why the cap exists")
    print(f"With situational modifiers capped at ±{MAX_SITUATIONAL_STEPS} steps vs uncapped,\n"
          "P(success) for a competent 5+5 profile at step 0:\n")
    print("| situational | capped | uncapped |")
    print("| --- | --- | --- |")
    def rate(cap: bool, situational: int):
        return exact_success_probability(
            candidate="C_skill_primary", stat=5, skill=5, difficulty=0,
            situational=situational, cap_situational=cap,
        )

    for situational in (0, 1, 2, 3, 4, 6):
        print(f"| +{situational} | {pct(rate(True, situational))} | {pct(rate(False, situational))} |")
    print("\nUncapped stacking walks a mere +6 out past the top of the ladder's own dice:")
    print("a single situational bonus becomes worth more than every die in the roll.")

    rule("8. Lethality — pace, not a final combat system")
    print("Expected exchanges to fill a 4-box stress track, defending at Everyday (DV 13):\n")
    print("| engine | weak 2+1 | competent 5+5 | mixed 10+1 | specialist 8+8 | top 10+10 |")
    print("| --- | --- | --- | --- | --- | --- |")
    legacy_cells = " | ".join(
        f"{legacy_takedown(stat=stat, skill=skill, target=13, stress=4, trials=2_000, seed=SEED + stat):.1f}"
        for _, stat, skill in PROFILES
    )
    print(f"| legacy 1d10 | {legacy_cells} |")
    for candidate in CANDIDATES:
        cells = " | ".join(
            f"{hits_to_takedown(candidate=candidate, stat=stat, skill=skill, defence=13, stress=4, trials=2_000, seed=SEED + stat):.1f}"
            for _, stat, skill in PROFILES
        )
        print(f"| `{candidate}` | {cells} |")
    print("\n#200 leaves the light wound ladder in place until it is reconciled, so this")
    print("measures how *fast* each engine resolves an exchange — not a proposed wound model.")

    rule("9. Where this prototype stands, stated rather than hidden")
    print("- **The DV collapse this prototype first reported is FIXED.** Its own draft divisor")
    print("  mapped 21 Heroic, 24 Incredible and 29 Legendary all onto +3. Issue #213 supplied")
    print("  an author-directed table, this prototype now CONSUMES it (see")
    print("  `data/rules/fudge_scale_migration.json`), and all seven authored DVs map onto seven")
    print("  distinct steps. Do not restate the mapping here -- change the author's file.")
    print("- **The rating and DV mappings are consumed, not invented.** Per AGENTS.md section 13,")
    print("  where a shared specification exists it is consumed rather than re-declared in a")
    print("  second runtime, so a change to that file moves these numbers and the tests say so.")
    print("- **A DV outside the authored seven falls back to the nearest one**, stated rather than")
    print("  silently interpolated: the table is defined on the authored difficulty set.")
    print("- **Ratings 1 and 10 are still partly wasted in the additive candidate**: a 10 already")
    print("  saturates the ladder alone, so a Skill can add nothing the STAT had not already given.")
    print("- **No aspects, stress or consequence model is proposed here.** #200 asks for those to")
    print("  be tested; they need their own prototype and their own playtest.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
